version: '3.8'
services:
    db:
        image: postgres:alpine3.21
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: alphawash_db_v3
        volumes:
          - pgdata:/var/lib/postgresql/data
          - ./init-db:/docker-entrypoint-initdb.d
        ports:
          - "5432:5432"
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U postgres" ]
          interval: 5s
          timeout: 5s
          retries: 5
    app:
      build: .
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL:  jdbc:postgresql://db:5432/alphawash_db_v3
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: root
      depends_on:
        db:
          condition: service_healthy
volumes:
    pgdata: