package com.alphawash.constant;

public class Constant {
    public static final String ROOT = "/";
    public static final String API = "/api";
    public static final String SEARCH_ENDPOINT = "/search";
    public static final String INSERT_ENDPOINT = "/insert";
    public static final String CREATE_ENDPOINT = "/create";
    public static final String UPDATE_ENDPOINT = "/update";
    public static final String CANCEL_ENDPOINT = "/cancel";
    public static final String DELETE_ENDPOINT = "/delete";
    public static final String CODE_PATH_PARAMETER = "/code/{code}";
    public static final String ID_PATH_PARAMETER = "/{id}";
    public static final String DELETE_WITH_PATH_PARAMETER = DELETE_ENDPOINT + "/{id}";
    public static final String UPDATE_WITH_PATH_PARAMETER = UPDATE_ENDPOINT + "/{id}";
    public static final String API_EMPLOYEE = API + "/employee";
    public static final String API_CUSTOMER = API + "/customer";
    public static final String API_BRANDS = API + "/brands";
    public static final String API_MODEL = API + "/model";
    public static final String API_ORDERS = API + "/orders";
    public static final String API_SERVICE_COMBO = API + "/combo";
    public static final String API_ORDER_DETAIL = API + "/order-detail";
    public static final String API_SERVICE = API + "/service";
    public static final String API_SERVICE_CATALOG = API + "/service-catalog";
    public static final String API_SERVICE_TYPE = API + "/service-type";
    public static final String API_SERVICE_CATEGORY = "/by-service-id";
    public static final String API_VEHICLE = API + "/vehicle";
    public static final String API_REVENUE = API + "/revenue";
    public static final String API_EMPLOYEE_SKILL = API + "/employee-skill";
    public static final String API_BRAND_WITH_MODELS = "/brands/with-models";
    public static final String API_CREATE_ORDER = "/create-order";
    public static final String API_QUICK_INVOICE = API + "/quick-invoice";
    public static final String API_AUTH = API + "/auth";
    public static final String LOGIN_ENDPOINT = "/login";
    public static final String API_PRODUCT_CATEGORIES = API + "/product-categories";
    public static final String API_SUPPLIERS = API + "/suppliers";
    public static final String API_PRODUCTS = API + "/products";
    public static final String API_INVENTORY = API + "/inventory";
    public static final String API_PURCHASE_ORDERS = API + "/purchase-orders";
    public static final String RECEIVE_ENDPOINT = "/receive";
    public static final String API_DASHBOARD = API + "/dashboard";
    public static final String API_CUSTOMER_SEGMENTS = API + "/customer-segments";
    public static final String ADMINISTRATOR = "admin";
    public static final int ZERO = 0;
}
