INSERT INTO model(model_name, code, size, brand_code) values('Mazda2','M0001', 'S','B0001');
INSERT INTO model(model_name, code, size, brand_code) values('CX-3','M0002', 'M','B0001');
INSERT INTO model(model_name, code, size, brand_code) values('Mazda3','M0003', 'M','B0001');
INSERT INTO model(model_name, code, size, brand_code) values('Mazda6','M0004', 'M','B0001');
INSERT INTO model(model_name, code, size, brand_code) values('CX-30','M0005', 'M','B0001');
INSERT INTO model(model_name, code, size, brand_code) values('CX-5','M0006', 'M','B0001');
INSERT INTO model(model_name, code, size, brand_code) values('CX-8','M0007', 'L','B0001');
INSERT INTO model(model_name, code, size, brand_code) values('BT-50','M0008', 'L','B0001');
INSERT INTO model(model_name, code, size, brand_code) values('GS8','M0009', 'M','B0002');
INSERT INTO model(model_name, code, size, brand_code) values('M8','M0010', 'L','B0002');
INSERT INTO model(model_name, code, size, brand_code) values('M6 Pro','M0011', 'M','B0002');
INSERT INTO model(model_name, code, size, brand_code) values('XC40','M0012', 'M','B0003');
INSERT INTO model(model_name, code, size, brand_code) values('XC60','M0013', 'M','B0003');
INSERT INTO model(model_name, code, size, brand_code) values('XC90','M0014', 'L','B0003');
INSERT INTO model(model_name, code, size, brand_code) values('V90','M0015', 'M','B0003');
INSERT INTO model(model_name, code, size, brand_code) values('V60 Cross Country','M0016', 'M','B0003');
INSERT INTO model(model_name, code, size, brand_code) values('S90','M0017', 'M','B0003');
INSERT INTO model(model_name, code, size, brand_code) values('Fadil','M0018', 'S','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('Lux A2.0','M0019', 'M','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('Lux SA2.0','M0020', 'M','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('President','M0021', 'L','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('e34','M0022', 'M','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('VF8','M0023', 'M','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('VF5','M0024', 'M','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('VF9','M0025', 'L','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('VF6','M0026', 'M','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('VF7','M0027', 'M','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('VF3','M0028', 'S','B0004');
INSERT INTO model(model_name, code, size, brand_code) values('H6','M0029', 'M','B0005');
INSERT INTO model(model_name, code, size, brand_code) values('Karoq','M0030', 'M','B0006');
INSERT INTO model(model_name, code, size, brand_code) values('Kodiaq','M0031', 'M','B0006');
INSERT INTO model(model_name, code, size, brand_code) values('1500','M0032', 'L','B0007');
INSERT INTO model(model_name, code, size, brand_code) values('DBX','M0033', 'L','B0008');
INSERT INTO model(model_name, code, size, brand_code) values('Lynk & Co 09','M0034', 'L','B0009');
INSERT INTO model(model_name, code, size, brand_code) values('Lynk & Co 06','M0035', 'M','B0009');
INSERT INTO model(model_name, code, size, brand_code) values('Lynk & Co 01','M0036', 'M','B0009');
INSERT INTO model(model_name, code, size, brand_code) values('Lynk & Co 05','M0037', 'M','B0009');
INSERT INTO model(model_name, code, size, brand_code) values('Lynk & Co 03','M0038', 'M','B0009');
INSERT INTO model(model_name, code, size, brand_code) values('Y Plus','M0039', 'M','B0010');
INSERT INTO model(model_name, code, size, brand_code) values('ES','M0040', 'M','B0010');
INSERT INTO model(model_name, code, size, brand_code) values('718','M0041', 'S','B0011');
INSERT INTO model(model_name, code, size, brand_code) values('911','M0042', 'M','B0011');
INSERT INTO model(model_name, code, size, brand_code) values('Taycan','M0043', 'M','B0011');
INSERT INTO model(model_name, code, size, brand_code) values('Panamera','M0044', 'M','B0011');
INSERT INTO model(model_name, code, size, brand_code) values('Macan','M0045', 'M','B0011');
INSERT INTO model(model_name, code, size, brand_code) values('Cayenne','M0046', 'L','B0011');
INSERT INTO model(model_name, code, size, brand_code) values('Macan EV','M0047', 'M','B0011');
INSERT INTO model(model_name, code, size, brand_code) values('Series 5','M0048', 'M','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('Series 7','M0049', 'L','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('X1','M0050', 'S','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('X3','M0051', 'M','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('X4','M0052', 'M','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('X6','M0053', 'M','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('Z4 Roadster','M0054', 'S','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('Series 3','M0055', 'M','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('X5','M0056', 'M','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('X7','M0057', 'L','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('Series 4','M0058', 'M','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('i7','M0059', 'L','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('Series 8','M0060', 'L','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('iX3','M0061', 'M','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('i4','M0062', 'M','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('XM','M0063', 'L','B0012');
INSERT INTO model(model_name, code, size, brand_code) values('A-class','M0064', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('C-Class','M0065', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('E-Class','M0066', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('S-Class','M0067', 'L','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('GLC','M0068', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('GLB','M0069', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('GLS','M0070', 'L','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('G-Class','M0071', 'L','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('GT-Coupe','M0072', 'L','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('V-Class','M0073', 'L','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('GLE','M0074', 'L','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('GLA','M0075', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('EQS','M0076', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('EQS SUV','M0077', 'L','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('EQB','M0078', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('EQE SUV','M0079', 'L','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('AMG SL','M0080', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('Maybach EQS SUV','M0081', 'L','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('C5','M0082', 'M','B0014');
INSERT INTO model(model_name, code, size, brand_code) values('2008','M0083', 'M','B0015');
INSERT INTO model(model_name, code, size, brand_code) values('3008','M0084', 'M','B0015');
INSERT INTO model(model_name, code, size, brand_code) values('5008','M0085', 'M','B0015');
INSERT INTO model(model_name, code, size, brand_code) values('Traveller','M0086', 'L','B0015');
INSERT INTO model(model_name, code, size, brand_code) values('408','M0087', 'M','B0015');
INSERT INTO model(model_name, code, size, brand_code) values('Polo','M0088', 'S','B0016');
INSERT INTO model(model_name, code, size, brand_code) values('Tiguan','M0089', 'M','B0016');
INSERT INTO model(model_name, code, size, brand_code) values('Passat','M0090', 'M','B0016');
INSERT INTO model(model_name, code, size, brand_code) values('T-Cross','M0091', 'M','B0016');
INSERT INTO model(model_name, code, size, brand_code) values('Touareg','M0092', 'M','B0016');
INSERT INTO model(model_name, code, size, brand_code) values('Virtus','M0093', 'M','B0016');
INSERT INTO model(model_name, code, size, brand_code) values('Viloran','M0094', 'L','B0016');
INSERT INTO model(model_name, code, size, brand_code) values('Teramont X','M0095', 'L','B0016');
INSERT INTO model(model_name, code, size, brand_code) values('Teramont','M0096', 'L','B0016');
INSERT INTO model(model_name, code, size, brand_code) values('mu-X','M0097', 'M','B0017');
INSERT INTO model(model_name, code, size, brand_code) values('D-Max','M0098', 'L','B0017');
INSERT INTO model(model_name, code, size, brand_code) values('A4','M0099', 'M','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('Q2','M0100', 'M','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('Q3','M0101', 'M','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('Q5','M0102', 'M','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('Q7','M0103', 'M','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('Q8','M0104', 'M','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('A8L','M0105', 'L','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('e-tron GT','M0106', 'M','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('Q8 e-tron','M0107', 'L','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('A6','M0108', 'M','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('A7','M0109', 'M','B0018');
INSERT INTO model(model_name, code, size, brand_code) values('XE','M0110', 'M','B0019');
INSERT INTO model(model_name, code, size, brand_code) values('XF','M0111', 'M','B0019');
INSERT INTO model(model_name, code, size, brand_code) values('F-Pace','M0112', 'M','B0019');
INSERT INTO model(model_name, code, size, brand_code) values('E-Pace','M0113', 'M','B0019');
INSERT INTO model(model_name, code, size, brand_code) values('F-Type','M0114', 'M','B0019');
INSERT INTO model(model_name, code, size, brand_code) values('ZS','M0115', 'M','B0020');
INSERT INTO model(model_name, code, size, brand_code) values('HS','M0116', 'M','B0020');
INSERT INTO model(model_name, code, size, brand_code) values('MG5','M0117', 'M','B0020');
INSERT INTO model(model_name, code, size, brand_code) values('RX5','M0118', 'M','B0020');
INSERT INTO model(model_name, code, size, brand_code) values('MG4 EV','M0119', 'M','B0020');
INSERT INTO model(model_name, code, size, brand_code) values('MG7','M0120', 'M','B0020');
INSERT INTO model(model_name, code, size, brand_code) values('Cyberster','M0121', 'M','B0020');
INSERT INTO model(model_name, code, size, brand_code) values('7X-E','M0122', 'M','B0021');
INSERT INTO model(model_name, code, size, brand_code) values('7X','M0123', 'M','B0021');
INSERT INTO model(model_name, code, size, brand_code) values('Navara','M0124', 'L','B0022');
INSERT INTO model(model_name, code, size, brand_code) values('Almera','M0125', 'M','B0022');
INSERT INTO model(model_name, code, size, brand_code) values('Kicks','M0126', 'M','B0022');
INSERT INTO model(model_name, code, size, brand_code) values('E-HS9','M0127', 'M','B0023');
INSERT INTO model(model_name, code, size, brand_code) values('H9','M0128', 'M','B0023');
INSERT INTO model(model_name, code, size, brand_code) values('Forester','M0129', 'M','B0024');
INSERT INTO model(model_name, code, size, brand_code) values('Outback','M0130', 'M','B0024');
INSERT INTO model(model_name, code, size, brand_code) values('BR-Z','M0131', 'S','B0024');
INSERT INTO model(model_name, code, size, brand_code) values('WRX','M0132', 'M','B0024');
INSERT INTO model(model_name, code, size, brand_code) values('Crosstrek','M0133', 'M','B0024');
INSERT INTO model(model_name, code, size, brand_code) values('3 Door','M0134', 'M','B0025');
INSERT INTO model(model_name, code, size, brand_code) values('5 Door','M0135', 'M','B0025');
INSERT INTO model(model_name, code, size, brand_code) values('Countryman','M0136', 'M','B0025');
INSERT INTO model(model_name, code, size, brand_code) values('JCW','M0137', 'M','B0025');
INSERT INTO model(model_name, code, size, brand_code) values('EcoSport','M0138', 'M','B0026');
INSERT INTO model(model_name, code, size, brand_code) values('Everest','M0139', 'M','B0026');
INSERT INTO model(model_name, code, size, brand_code) values('Ranger','M0140', 'M','B0026');
INSERT INTO model(model_name, code, size, brand_code) values('Explorer','M0141', 'M','B0026');
INSERT INTO model(model_name, code, size, brand_code) values('Territory','M0142', 'M','B0026');
INSERT INTO model(model_name, code, size, brand_code) values('Ranger Raptor','M0143', 'M','B0026');
INSERT INTO model(model_name, code, size, brand_code) values('IS','M0144', 'S','B0027');
INSERT INTO model(model_name, code, size, brand_code) values('LS','M0145', 'M','B0027');
INSERT INTO model(model_name, code, size, brand_code) values('NX','M0146', 'M','B0027');
INSERT INTO model(model_name, code, size, brand_code) values('RX','M0147', 'M','B0027');
INSERT INTO model(model_name, code, size, brand_code) values('LX','M0148', 'M','B0027');
INSERT INTO model(model_name, code, size, brand_code) values('LM','M0149', 'M','B0027');
INSERT INTO model(model_name, code, size, brand_code) values('GX','M0150', 'M','B0027');
INSERT INTO model(model_name, code, size, brand_code) values('Wrangler','M0151', 'M','B0028');
INSERT INTO model(model_name, code, size, brand_code) values('Gladiator','M0152', 'M','B0028');
INSERT INTO model(model_name, code, size, brand_code) values('Grand Cherokee L','M0153', 'M','B0028');
INSERT INTO model(model_name, code, size, brand_code) values('Atto 3','M0154', 'M','B0029');
INSERT INTO model(model_name, code, size, brand_code) values('Seal','M0155', 'M','B0029');
INSERT INTO model(model_name, code, size, brand_code) values('Dolphin','M0156', 'M','B0029');
INSERT INTO model(model_name, code, size, brand_code) values('M6','M0157', 'M','B0029');
INSERT INTO model(model_name, code, size, brand_code) values('Han','M0158', 'M','B0029');
INSERT INTO model(model_name, code, size, brand_code) values('City','M0159', 'M','B0030');
INSERT INTO model(model_name, code, size, brand_code) values('HR-V','M0160', 'M','B0030');
INSERT INTO model(model_name, code, size, brand_code) values('CR-V','M0161', 'M','B0030');
INSERT INTO model(model_name, code, size, brand_code) values('Accord','M0162', 'M','B0030');
INSERT INTO model(model_name, code, size, brand_code) values('Brio','M0163', 'M','B0030');
INSERT INTO model(model_name, code, size, brand_code) values('Civic','M0164', 'M','B0030');
INSERT INTO model(model_name, code, size, brand_code) values('Civic Type R','M0165', 'M','B0030');
INSERT INTO model(model_name, code, size, brand_code) values('BR-V','M0166', 'M','B0030');
INSERT INTO model(model_name, code, size, brand_code) values('Flying Spur','M0167', 'M','B0031');
INSERT INTO model(model_name, code, size, brand_code) values('Bentayga','M0168', 'M','B0031');
INSERT INTO model(model_name, code, size, brand_code) values('Continental','M0169', 'M','B0031');
INSERT INTO model(model_name, code, size, brand_code) values('Levante','M0170', 'M','B0032');
INSERT INTO model(model_name, code, size, brand_code) values('Ghibli','M0171', 'M','B0032');
INSERT INTO model(model_name, code, size, brand_code) values('Quattroporte','M0172', 'M','B0032');
INSERT INTO model(model_name, code, size, brand_code) values('Grecale','M0173', 'M','B0032');
INSERT INTO model(model_name, code, size, brand_code) values('GranTurismo','M0174', 'M','B0032');
INSERT INTO model(model_name, code, size, brand_code) values('Attrage','M0175', 'M','B0033');
INSERT INTO model(model_name, code, size, brand_code) values('Outlander','M0176', 'M','B0033');
INSERT INTO model(model_name, code, size, brand_code) values('Triton','M0177', 'M','B0033');
INSERT INTO model(model_name, code, size, brand_code) values('Pajero Sport','M0178', 'M','B0033');
INSERT INTO model(model_name, code, size, brand_code) values('Xpander','M0179', 'M','B0033');
INSERT INTO model(model_name, code, size, brand_code) values('Xforce','M0180', 'M','B0033');
INSERT INTO model(model_name, code, size, brand_code) values('i10','M0181', 'S','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Accent','M0182', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Kona','M0183', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Elantra','M0184', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Tucson','M0185', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Santa Fe','M0186', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Creta','M0187', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Stargazer','M0188', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Ioniq 5','M0189', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Custin','M0190', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Palisade','M0191', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Venue','M0192', 'M','B0034');
INSERT INTO model(model_name, code, size, brand_code) values('Hongguang Mini EV','M0193', 'S','B0035');
INSERT INTO model(model_name, code, size, brand_code) values('Bingo','M0194', 'M','B0035');
INSERT INTO model(model_name, code, size, brand_code) values('Wigo','M0195', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Vios','M0196', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Corolla Altis','M0197', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Camry','M0198', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Rush','M0199', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Avanza','M0200', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Innova','M0201', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Fortuner','M0202', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Granvia','M0203', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Land Cruiser LC300','M0204', 'L','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Land Cruiser Prado','M0205', 'L','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Corolla Cross','M0206', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Hilux','M0207', 'L','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Alphard','M0208', 'L','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Yaris','M0209', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Raize','M0210', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Avanza Premio','M0211', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Veloz Cross','M0212', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Yaris Cross','M0213', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Innova Cross','M0214', 'M','B0036');
INSERT INTO model(model_name, code, size, brand_code) values('Swift','M0215', 'M','B0037');
INSERT INTO model(model_name, code, size, brand_code) values('Ciaz','M0216', 'M','B0037');
INSERT INTO model(model_name, code, size, brand_code) values('Ertiga','M0217', 'M','B0037');
INSERT INTO model(model_name, code, size, brand_code) values('XL7','M0218', 'M','B0037');
INSERT INTO model(model_name, code, size, brand_code) values('Jimny','M0219', 'M','B0037');
INSERT INTO model(model_name, code, size, brand_code) values('Morning','M0220', 'S','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Soluto','M0221', 'S','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Cerato','M0222', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Optima','M0223', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Sorento','M0224', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Rondo','M0225', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Quoris','M0226', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('K3','M0227', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Carnival','M0228', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Sonet','M0229', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('K5','M0230', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Sportage','M0231', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Carens','M0232', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Seltos','M0233', 'M','B0038');
INSERT INTO model(model_name, code, size, brand_code) values('Range Rover Velar','M0234', 'M','B0039');
INSERT INTO model(model_name, code, size, brand_code) values('Range Rover Evoque','M0235', 'M','B0039');
INSERT INTO model(model_name, code, size, brand_code) values('Range Rover','M0236', 'M','B0039');
INSERT INTO model(model_name, code, size, brand_code) values('Range Rover Sport','M0237', 'M','B0039');
INSERT INTO model(model_name, code, size, brand_code) values('Discovery','M0238', 'M','B0039');
INSERT INTO model(model_name, code, size, brand_code) values('Discovery Sport','M0239', 'L','B0039');
INSERT INTO model(model_name, code, size, brand_code) values('Defender 90','M0240', 'L','B0039');
INSERT INTO model(model_name, code, size, brand_code) values('Defender 110','M0241', 'L','B0039');
INSERT INTO model(model_name, code, size, brand_code) values('Defender 130','M0242', 'L','B0039');
INSERT INTO model(model_name, code, size, brand_code) values('Grandis','M0243', 'M','B0033');
INSERT INTO model(model_name, code, size, brand_code) values('Trailblazer','M0244', 'M','B0041');
INSERT INTO model(model_name, code, size, brand_code) values('Beijing X7','M0245', 'L','B0040');
INSERT INTO model(model_name, code, size, brand_code) values('Oulander','M0246', 'M','B0033');
INSERT INTO model(model_name, code, size, brand_code) values('Focus','M0247', 'M','B0026');
INSERT INTO model(model_name, code, size, brand_code) values('GLA','M0248', 'M','B0013');
INSERT INTO model(model_name, code, size, brand_code) values('Terra','M0249', 'L','B0022');
INSERT INTO model(model_name, code, size, brand_code) values('Sienna','M0250', 'L','B0036');